name: build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
        with:
          node-version: '20.5.1'
      - run: ls -l front
      - run: pwd
      - run: npm install
      - run: cd front && npm install && cd ..
      - run: cd electron_app && npm install && cd ..
      - run: npm run build:electron
      
    
      
